### ISSUE TITLE
Adding "#" in front of d.ts library name breaks editor -- with no recovery on reload!

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#517]
Repro (can repro in just regular browser with web snippet, on localhost)
1. Open regular snippet
2. Put an "#" in front of `@microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts`.  It seems to be just that one.

Will get an error:

```
Access to fetch at 'https://unpkg.com/#@microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts' from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.chunk.js:10726 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://unpkg.com/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ main.chunk.js:10726
(anonymous) @ main.chunk.js:10725
...
Emitter.fire @ event.ts:123
(anonymous) @ textAreaInput.ts:242
index.js:1452 uncaught at rootSaga at rootSaga 
 at rootSaga 
 at takeEvery 
 at setIntellisenseFilesSaga 
 TypeError: Failed to fetch
```

After this, the editor becomes mostly unresponsive.  And is even unresponsive on reload.  Requires clearing localstorage (!) to get it back to working.

**Comment by Zlatkovsky** [comment]
Note: I'm somewhat less concerned about the particular bug, and more concerned about other such errors in sagas.

**Comment by Zlatkovsky** [comment]
This looks identical to a bug that Shahzeb/Aaron found, email from Dec 20th (with repro steps send by Shahzeb on Dec 28).  We can use this bug to track both, since they are one of the same.

**Comment by Zlatkovsky** [comment]
@jakobpn , FYI, this is the bug you just re-ran into.

**Comment by Zlatkovsky** [comment]
Turns out my fix above does **NOT** fix the issue.
You can still get errors like:

```
utils.js:262 uncaught at ba at ba 
 at ba 
 at l 
 at mi 
 Error: https://unpkg.com/@types/office-js/index.d.ts already a extra lib
    at e.addExtraLib (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-14-3/vs/editor/editor.main.js:1893:784)
    at https://script-lab-react-beta.azurewebsites.net/static/js/main.824e0136.chunk.js:1:108123
F @ utils.js:262
k @ proc.js:245
```

With a snippet like https://gist.github.com/JuaneloJuanelo/1c744b266cdfe54c2aa306339eaafe3a

So need to fix at a more fundamental level.
