### ISSUE TITLE
Login to GitHub not working in Office Online

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#661]
The error is from being propagated from OfficeHelpers after authentication is complete. When it tries to close the dialog OfficeHelpers receives and error from office.js

Error that causes Script Lab to fail:
 

Stack trace:

TypeError: Cannot read property 'messageParent' of undefined
    at Function.Dialog.close (https://script-lab.azureedge.net/bundles/vendor.e43b56b9965bb9f32678.bundle.js:1:373551)
    at Function.Authenticator.isAuthDialog (https://script-lab.azureedge.net/bundles/vendor.e43b56b9965bb9f32678.bundle.js:1:786790)
    at https://script-lab.azureedge.net/bundles/main.2318d5c75d501cc5651a.bundle.js:1:703673
    at step (https://script-lab.azureedge.net/bundles/main.2318d5c75d501cc5651a.bundle.js:1:702644)
    at Object.k.__generator.n [as next] (https://script-lab.azureedge.net/bundles/main.2318d5c75d501cc5651a.bundle.js:1:701973)
    at fulfilled (https://script-lab.azureedge.net/bundles/main.2318d5c75d501cc5651a.bundle.js:1:701681)
    at ZoneDelegate.invoke (https://script-lab.azureedge.net/bundles/polyfills.41a27b05ae4f793dfc09.bundle.js:1:85192)
    at Zone.run (https://script-lab.azureedge.net/bundles/polyfills.41a27b05ae4f793dfc09.bundle.js:1:80018)
    at https://script-lab.azureedge.net/bundles/polyfills.41a27b05ae4f793dfc09.bundle.js:1:77231
    at ZoneDelegate.invokeTask (https://script-lab.azureedge.net/bundles/polyfills.41a27b05ae4f793dfc09.bundle.js:1:85935)
    at Zone.runTask (https://script-lab.azureedge.net/bundles/polyfills.41a27b05ae4f793dfc09.bundle.js:1:80709)
    at drainMicroTaskQueue (https://script-lab.azureedge.net/bundles/polyfills.41a27b05ae4f793dfc09.bundle.js:1:75411)
    at <anonymous>

Source of the problem:
 

Essentially UI is undefined (why? needs to be determined)… 
In the network logs for the dialog I don’t see the call to load office.js going…

 

Yes the script is included.
 

Notice my cache is also disabled.

**Comment by Zlatkovsky** [comment]
BTW, could it be related to https://github.com/OfficeDev/script-lab/issues/290?
