### ISSUE TITLE
Blocker Monaco 0.16.1: Exception when switching to HTML and back

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#672]
When switching back and forth between HTML and JS, can get into this error:

```
"TypeError: Object doesn't support property or method 'assign'\n   at TemplatablePattern (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:12230:3)\n   at Tokenizer (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:13378:3)\n   at Beautifier.prototype.beautify (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:12712:3)\n   at style_html (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:12409:3)\n   at html_beautify (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:13636:17)\n   at format (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:13749:9)\n   at HTMLWorker.prototype.format (https://localhost:3000/external/monaco-editor-0-16-1/vs/language/html/htmlWorker.js:15094:13)\n   at BaseEditorSimpleWorker.prototype.fmr (https://localhost:3000/external/monaco-editor-0-16-1/vs/base/worker/workerMain.js#html:9439:17)\n   at SimpleWorkerServer.prototype._handleMessage (https://localhost:3000/external/monaco-editor-0-16-1/vs/base/worker/workerMain.js#html:5982:17)\n   at handleMessage (https://localhost:3000/external/monaco-editor-0-16-1/vs/base/worker/workerMain.js#html:5968:58)"
```

**Update:** it looks like the underlying issue is the Format Document action that gets called when switching tabs.  So you can either repro it by switching tabs, or by clicking "format document" within the HTML tab.

**Comment by Zlatkovsky** [comment]
Blocked by https://github.com/Microsoft/monaco-editor/issues/1367
