### ISSUE TITLE
Code pane crash when switching between snippets

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#718]
### Bug Report

- **Host**: Excel
- **OS**: Windows
- **Browser**: Win32
- **Environment**: Beta

#### Steps to Reproduce:

This happened when rapidly switching between snippets.

#### Failure Logs:

Error Message:

Script Lab

An unexpected error has occurred.
Unable to get property 'getPositionAt' of undefined or null reference

TypeError: Unable to get property 'getPositionAt' of undefined or null reference
   at e.prototype._offsetToPosition (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/language/typescript/tsMode.js:7:4498)
   at e.prototype._textSpanToRange (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/language/typescript/tsMode.js:7:4592)
   at Anonymous function (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/language/typescript/tsMode.js:7:10636)
   at o (https://script-lab-react-beta.azurewebsites.net/static/js/2.5b5f17ec.chunk.js:1:3080955)
   at Anonymous function (https://script-lab-react-beta.azurewebsites.net/static/js/2.5b5f17ec.chunk.js:1:3081102)
   at c (https://script-lab-react-beta.azurewebsites.net/static/js/2.5b5f17ec.chunk.js:1:2401917)

**Comment by Zlatkovsky** [comment]
I've seen this bug occasionally too.  Unfortunately, it is very hard to repro.  We need to understand what exactly causes it and come up with a minimal repro to understand if it's even our bug vs. Monaco bug.

**Comment by ElizabethSamuel-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
