### ISSUE TITLE
Unexpected error when swtiching between code pane tabs

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#760]
### Bug Report

- **Host**: Excel
- **OS**: Windows
- **Browser**: win32
- **Environment**: Beta

#### Actual behavior:

Switching between the **Libraries** and **Script** tabs caused an unexcepted error (log below).

#### Steps to Reproduce:

1. Open a snippet
2. Rapidly switch between tabs in the code pane.

#### Failure Logs:

Script Lab
An unexpected error has occurred.
Unable to get property 'getText' of undefined or null reference

TypeError: Unable to get property 'getText' of undefined or null reference
   at t.findDocumentLinks (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/language/html/htmlWorker.js:7:328727)
   at e.prototype.findDocumentLinks (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/language/html/htmlWorker.js:7:340232)
   at t.prototype.fmr (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:141:1)
   at e.prototype._handleMessage (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:88:148)
   at handleMessage (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:87:691)
   at e.prototype._handleMessage (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:85:883)
   at e.prototype.handleMessage (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:85:394)
   at e.prototype.onmessage (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:87:764)
   at self.onmessage (https://script-lab-react-beta.azurewebsites.net/external/monaco-editor-0-16-2/vs/base/worker/workerMain.js#html:142:382)

**Comment by Zlatkovsky** [comment]
@AlexJerabek , is the issue intermittent, or is it happening all the time?

**Comment by AlexJerabek** [comment]
I can cause the crash fairly consistently. It's more likely to happen when freshly loading Excel and Script Lab.

**Comment by Zlatkovsky** [comment]
@AlexJerabek , I believe this should be fixed with the deployment from an hour ago (whereby we upgraded to a newer version of Monaco, and should hopefully stop seeing those intermittent issues).
