### ISSUE TITLE
[Outlook] Getting error when try to set start property in Appointment Compose

### ISSUE THREAD

**Issue by ElizabethSamuel-MSFT** [OfficeDev/script-lab#798]
### Bug Report

- **Host**: Outlook
- **OS**: Windows
- **Browser**: Edge
- **Environment**: alpha

#### Expected behavior:

Calling setAsync and getAsync on Office.context.mailbox.item.start while composing an appointment should succeed.

#### Actual behavior:

Get errors instead.

`getAsync` error:
[ERROR]: [
    "Uncaught TypeError: Office.context.mailbox.item.start.getAsync is not a function",
    "https://script-lab-react-runner-alpha.azurewebsites.net/?officejs=https%3A%2F%2Fappsforoffice.microsoft.com%2Flib%2F1%2Fhosted%2Foffice.js",
    5,
    39,
    TypeError: Office.context.mailbox.item.start.getAsync is not a function
]

`setAsync` error:
[ERROR]: [
    "Uncaught TypeError: Office.context.mailbox.item.start.setAsync is not a function",
    "https://script-lab-react-runner-alpha.azurewebsites.net/?officejs=https%3A%2F%2Fappsforoffice.microsoft.com%2Flib%2F1%2Fhosted%2Foffice.js",
    10,
    39,
    TypeError: Office.context.mailbox.item.start.setAsync is not a function
]

#### Steps to Reproduce:

1. Open OWA (not sure about other clients) and start composing an appointment
2. Run "Get and set the start date and time (Appointment Organizer)" snippet in Script Lab
(snippet yaml: https://github.com/OfficeDev/office-js-snippets/blob/master/samples/outlook/90-other-item-apis/get-set-start-appointment-organizer.yaml)

**Comment by ElizabethSamuel-MSFT** [comment]
Seeing similar errors when try to getAsync and setAsync end property.

**Comment by ElizabethSamuel-MSFT** [comment]
Seeing similar errors when try to getAsync and setAsync location property.

**Comment by ElizabethSamuel-MSFT** [comment]
Determined that error was due to my not being in edit mode of my appointment. However, still getting an error when attempting to set the start property:

[ERROR]: [
    "Uncaught Sys.ArgumentTypeException: Sys.ArgumentTypeException: Object of type 'object' cannot be converted to type 'function'.
    Parameter name: dateTime",
    "https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.alpha.js",
    19,
    267825,
    Error:
    {
        "stack": "Sys.ArgumentTypeException: Sys.ArgumentTypeException: Object of type 'object' cannot be converted to type 'function'.\nParameter name: dateTime\n    at j (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.alpha.js:19:214211)\n    at z (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.alpha.js:19:215335)\n    at Fr (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.alpha.js:19:267831)\n    at Object.<anonymous> (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.alpha.js:19:267692)\n    at HTMLButtonElement.set (<anonymous>:19:39)\n    at HTMLButtonElement.dispatch (https://unpkg.com/jquery@3.1.1/dist/jquery.js:5201:27)\n    at HTMLButtonElement.elemData.handle (https://unpkg.com/jquery@3.1.1/dist/jquery.js:5009:28)",
        "message": "Sys.ArgumentTypeException: Object of type 'object' cannot be converted to type 'function'.\nParameter name: dateTime",
        "name": "Sys.ArgumentTypeException",
        "paramName": "dateTime",
        "actualType": "object",
        "expectedType": "function"
    }
]

**Comment by ElizabethSamuel-MSFT** [comment]
No longer reproing this issue so closing.
