### ISSUE TITLE
Sript lab custom function feature does not work

### ISSUE THREAD

**Issue by Vladyslav42v** [OfficeDev/script-lab#906]
### Bug Report

- Microsoft® Excel® 2019 MSO (16.0.14131.20278) 32-bit 
- Windows
- Prod

How to reproduce:
 Ribbon -> Script lab -> Funtions

#### Actual behavior:
When I try to access script lab custom functions feature I am greeted with message. So the issue is not even in some particular function, the whole feature does not work.

Error:
{
    "stack": "RichApi.Error: There was an internal error while processing the request.\n    at new n (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:235928)\n    at n.o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:299150)\n    at https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:297255",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "CustomFunctionManager.register",
        "statement": "v.register(...);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var v = Microsoft.ExcelServices.CustomFunctionManager.newObject();",
            "// >>>>>",
            "v.register(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}

#### Screenshot:

![image](https://user-images.githubusercontent.com/45950773/126994186-303ac133-557c-45bd-a369-fe77370d36a0.png)

**Comment by chenxizhang** [comment]
![image](https://user-images.githubusercontent.com/1996954/188318412-06fc8238-d8ef-4651-a0c3-6d636dd1155e.png)

**Comment by davit-Margvelashvili** [comment]
Custom functions return #Bussy error even while using simple sample code like 'spherevolume'
