### ISSUE TITLE
custom function does not get registered and shows error message

### ISSUE THREAD

**Issue by colors256** [OfficeDev/script-lab#956]
1. In Excel 2019 
open Script Lab

2. create a custom function for test as follows

/** 
 * @customFunction
 */

function add(first: number, second: number){
 return (first+second);
 };
 
3. then click on the register button.

4. you get the following error message.

An unexpected error has occurred.
Error:
{
    "description": "There was an internal error while processing the request.",
    "message": "There was an internal error while processing the request.",
    "stack": "GeneralException: There was an internal error while processing the request.\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:304020)\n   at o (https://script-lab.azureedge.net/static/js/3.8791b5f9.chunk.js:2:3490823)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/3.8791b5f9.chunk.js:2:3490970)\n   at c (https://script-lab.azureedge.net/static/js/3.8791b5f9.chunk.js:2:2847852)",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "CustomFunctionManager.status",
        "statement": "v.load([\"status\"]);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var v = Microsoft.ExcelServices.CustomFunctionManager.newObject();",
            "// >>>>>",
            "v.load([\"status\"]);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}

**Comment by colors256** [comment]
seems like this only works with office 365 and not office 2019.
